export const checklists = [
  {
    slug: 'excavation',
    title: 'Excavation Checklist',
    level: 'Basic',
    shortDesc:
      'Site marking, levels, trench safety, depth checking, dewatering and earthwork quality checklist.',
    tags: ['Marking', 'Level', 'Safety', 'Depth'],
    purpose:
      'Excavation checklist helps site engineers verify line, level, depth, safety and soil condition before foundation work starts.',
    beforeWork: [
      'Check approved drawing and foundation layout.',
      'Verify grid lines and center lines on site.',
      'Confirm excavation depth and foundation size.',
      'Check benchmark level and reference level.',
      'Ensure underground utilities are identified.',
      'Arrange barricading around excavation area.',
    ],
    duringWork: [
      'Check excavation length, width and depth regularly.',
      'Avoid over excavation below required level.',
      'Remove loose soil from bottom surface.',
      'Provide side slope or shoring if soil is loose.',
      'Keep excavated soil away from trench edge.',
      'Arrange dewatering if water is present.',
    ],
    afterWork: [
      'Verify final depth with level instrument.',
      'Check bottom surface is clean and compact.',
      'Confirm foundation size before PCC.',
      'Take site photos before PCC work.',
      'Get approval from engineer/client before next activity.',
    ],
    qualityChecks: [
      'Line and level check',
      'Excavation depth check',
      'Soil condition check',
      'Bottom compaction check',
      'Dewatering check',
    ],
    commonMistakes: [
      'Excavating without proper marking.',
      'Ignoring benchmark level.',
      'Keeping soil too close to excavation edge.',
      'Starting PCC without cleaning loose soil.',
      'No barricading around excavation area.',
    ],
    safety: [
      'Provide barricades and warning tape.',
      'Do not allow workers near unsupported deep excavation.',
      'Keep heavy machines away from trench edge.',
      'Use helmet, safety shoes and reflective jacket.',
    ],
  },
  {
    slug: 'pcc',
    title: 'PCC Checklist',
    level: 'Basic',
    shortDesc:
      'Plain cement concrete checklist for surface preparation, thickness, mix, compaction and curing.',
    tags: ['PCC', 'Level', 'Thickness', 'Curing'],
    purpose:
      'PCC checklist ensures a clean, level and stable base is prepared before footing or foundation concrete.',
    beforeWork: [
      'Check excavation bottom is clean and compacted.',
      'Confirm PCC thickness from drawing.',
      'Check shuttering or side form if required.',
      'Verify concrete grade or mix ratio.',
      'Ensure water is not standing on excavation bed.',
    ],
    duringWork: [
      'Place PCC uniformly over prepared surface.',
      'Maintain required thickness.',
      'Use proper compaction or tamping.',
      'Check top level during placing.',
      'Avoid adding excess water.',
    ],
    afterWork: [
      'Check final PCC level.',
      'Ensure surface is finished properly.',
      'Start curing after initial setting.',
      'Do not place reinforcement until PCC is ready.',
    ],
    qualityChecks: [
      'Thickness check',
      'Level check',
      'Mix ratio check',
      'Surface finish check',
      'Curing check',
    ],
    commonMistakes: [
      'PCC placed over loose soil.',
      'Wrong PCC thickness.',
      'No level checking.',
      'Poor compaction.',
      'No curing.',
    ],
    safety: [
      'Use gloves while handling concrete.',
      'Avoid direct skin contact with cement slurry.',
      'Keep work area clear from unnecessary tools.',
    ],
  },
  {
    slug: 'footing',
    title: 'Footing Checklist',
    level: 'Intermediate',
    shortDesc:
      'Footing reinforcement, cover, shuttering, level, concrete grade and pre-pour checklist.',
    tags: ['Rebar', 'Cover', 'Concrete', 'Level'],
    purpose:
      'Footing checklist helps verify reinforcement, cover, dimensions, level and concrete readiness before footing casting.',
    beforeWork: [
      'Check footing size as per structural drawing.',
      'Verify footing reinforcement diameter and spacing.',
      'Check bottom and side cover blocks.',
      'Confirm column starter bars location.',
      'Check development length and anchorage.',
      'Ensure shuttering is rigid and aligned.',
    ],
    duringWork: [
      'Check concrete grade before pouring.',
      'Ensure concrete is poured evenly.',
      'Use vibrator properly for compaction.',
      'Avoid displacement of reinforcement.',
      'Maintain top level of footing.',
    ],
    afterWork: [
      'Check top finish and level.',
      'Protect starter bars from disturbance.',
      'Start curing on time.',
      'Remove shuttering only after sufficient setting.',
    ],
    qualityChecks: [
      'Bar diameter and spacing check',
      'Cover block check',
      'Column starter alignment',
      'Concrete grade check',
      'Vibration and compaction check',
    ],
    commonMistakes: [
      'Wrong bar spacing.',
      'Insufficient cover.',
      'Column starter bars not aligned.',
      'Concrete poured without checking reinforcement.',
      'Poor vibration causing honeycombing.',
    ],
    safety: [
      'Use gloves while tying reinforcement.',
      'Ensure safe access around footing area.',
      'Keep vibrator cable away from water.',
    ],
  },
  {
    slug: 'column',
    title: 'Column Checklist',
    level: 'Intermediate',
    shortDesc:
      'Column reinforcement, starter bars, stirrups, cover, shuttering alignment and concrete checklist.',
    tags: ['Column', 'Stirrups', 'Alignment', 'Concrete'],
    purpose:
      'Column checklist ensures vertical alignment, reinforcement detailing, cover and shuttering quality before column casting.',
    beforeWork: [
      'Check column location from grid lines.',
      'Verify main bar diameter and number.',
      'Check stirrup diameter and spacing.',
      'Check lap length and staggered laps.',
      'Provide cover blocks on all sides.',
      'Check shuttering alignment and verticality.',
    ],
    duringWork: [
      'Pour concrete in layers.',
      'Use needle vibrator properly.',
      'Avoid segregation during pouring.',
      'Check shuttering leakage.',
      'Ensure reinforcement cage does not shift.',
    ],
    afterWork: [
      'Check column surface after deshuttering.',
      'Check honeycombing if any.',
      'Start curing immediately.',
      'Verify column verticality after casting.',
    ],
    qualityChecks: [
      'Verticality check',
      'Stirrup spacing check',
      'Cover check',
      'Lap length check',
      'Honeycombing check',
    ],
    commonMistakes: [
      'Column not in plumb.',
      'Stirrups spacing incorrect.',
      'Cover blocks missing.',
      'Concrete poured from excessive height.',
      'Poor vibration.',
    ],
    safety: [
      'Use proper working platform.',
      'Do not climb on reinforcement cage.',
      'Secure column shuttering properly.',
    ],
  },
  {
    slug: 'beam',
    title: 'Beam Checklist',
    level: 'Intermediate',
    shortDesc:
      'Beam reinforcement, stirrups, bottom bars, top bars, supports, shuttering and concrete checklist.',
    tags: ['Beam', 'Rebar', 'Stirrups', 'Shuttering'],
    purpose:
      'Beam checklist helps site engineers verify beam reinforcement, support condition, shuttering, cover and casting quality.',
    beforeWork: [
      'Check beam size from drawing.',
      'Verify bottom bars and top bars.',
      'Check stirrup spacing near supports and midspan.',
      'Check beam-column junction reinforcement.',
      'Provide proper cover blocks.',
      'Check beam bottom level and shuttering support.',
    ],
    duringWork: [
      'Pour concrete carefully near beam-column joints.',
      'Use vibrator without disturbing reinforcement.',
      'Avoid shuttering leakage.',
      'Maintain concrete continuity.',
    ],
    afterWork: [
      'Check beam side surface after deshuttering.',
      'Start curing properly.',
      'Do not remove props early.',
      'Check cracks or honeycombing.',
    ],
    qualityChecks: [
      'Beam depth and width check',
      'Reinforcement placement check',
      'Stirrup spacing check',
      'Cover check',
      'Formwork level check',
    ],
    commonMistakes: [
      'Wrong stirrup spacing near supports.',
      'Missing extra top bars.',
      'Insufficient cover.',
      'Early removal of props.',
      'Poor compaction at junctions.',
    ],
    safety: [
      'Check staging and props before casting.',
      'Use safe working platform.',
      'Do not overload beam shuttering before casting.',
    ],
  },
  {
    slug: 'slab',
    title: 'Slab Checklist',
    level: 'Intermediate',
    shortDesc:
      'Slab reinforcement, cover, electrical conduits, level, shuttering, concrete and curing checklist.',
    tags: ['Slab', 'Rebar', 'Conduits', 'Curing'],
    purpose:
      'Slab checklist ensures reinforcement, formwork, level, MEP sleeves and concrete quality are verified before slab casting.',
    beforeWork: [
      'Check slab thickness from drawing.',
      'Verify main and distribution bar spacing.',
      'Check top extra bars near supports.',
      'Provide chairs for top reinforcement.',
      'Check electrical conduits and sleeves.',
      'Check shuttering level and supports.',
    ],
    duringWork: [
      'Pour concrete panel-wise.',
      'Use vibrator carefully.',
      'Maintain slab thickness.',
      'Avoid disturbing electrical conduits.',
      'Check surface level during finishing.',
    ],
    afterWork: [
      'Start curing after setting.',
      'Keep slab wet for required curing period.',
      'Do not remove props early.',
      'Check surface cracks and honeycombing.',
    ],
    qualityChecks: [
      'Bar spacing check',
      'Cover check',
      'Top bar support check',
      'Conduit placement check',
      'Slab level check',
    ],
    commonMistakes: [
      'Top reinforcement not supported properly.',
      'Electrical conduits placed incorrectly.',
      'Slab thickness variation.',
      'Poor curing.',
      'Early prop removal.',
    ],
    safety: [
      'Check slab staging before casting.',
      'Provide safe access for workers.',
      'Avoid overcrowding during concrete pour.',
    ],
  },
  {
    slug: 'brickwork',
    title: 'Brickwork Checklist',
    level: 'Basic',
    shortDesc:
      'Brick quality, soaking, line, level, mortar joint, curing and masonry checklist.',
    tags: ['Brick', 'Mortar', 'Line', 'Curing'],
    purpose:
      'Brickwork checklist ensures correct masonry line, level, bond, mortar thickness and curing.',
    beforeWork: [
      'Check brick quality and size.',
      'Soak bricks before use if required.',
      'Check wall layout and line.',
      'Prepare mortar as per required ratio.',
      'Clean base surface before starting masonry.',
    ],
    duringWork: [
      'Maintain proper bond pattern.',
      'Keep mortar joint thickness uniform.',
      'Check verticality and alignment regularly.',
      'Avoid dry bricks sucking water from mortar.',
      'Fill vertical joints properly.',
    ],
    afterWork: [
      'Rake joints if plaster is required.',
      'Cure brickwork properly.',
      'Protect fresh masonry from rain and vibration.',
      'Check wall line and plumb.',
    ],
    qualityChecks: [
      'Brick quality check',
      'Mortar ratio check',
      'Joint thickness check',
      'Line and plumb check',
      'Curing check',
    ],
    commonMistakes: [
      'Using dry bricks.',
      'Thick mortar joints.',
      'No proper bond.',
      'Poor curing.',
      'Wall not in plumb.',
    ],
    safety: [
      'Use stable scaffolding.',
      'Do not stack bricks unsafely at height.',
      'Use gloves while handling bricks.',
    ],
  },
  {
    slug: 'plaster',
    title: 'Plaster Checklist',
    level: 'Basic',
    shortDesc:
      'Surface preparation, hacking, chicken mesh, mortar ratio, thickness, level and curing checklist.',
    tags: ['Plaster', 'Mesh', 'Thickness', 'Finish'],
    purpose:
      'Plaster checklist helps ensure good bonding, proper thickness, level surface and crack control.',
    beforeWork: [
      'Clean wall surface properly.',
      'Complete hacking on RCC surface.',
      'Fix chicken mesh at RCC-masonry junctions.',
      'Check electrical conduit chasing is completed.',
      'Wet the surface before plastering.',
    ],
    duringWork: [
      'Maintain specified mortar ratio.',
      'Check plaster thickness.',
      'Use level dots and screeds.',
      'Finish surface uniformly.',
      'Avoid adding excess water.',
    ],
    afterWork: [
      'Start curing after setting.',
      'Cure for sufficient days.',
      'Check cracks, hollowness and uneven surface.',
      'Repair defects before painting.',
    ],
    qualityChecks: [
      'Surface preparation check',
      'Chicken mesh check',
      'Thickness check',
      'Line and level check',
      'Hollowness check',
    ],
    commonMistakes: [
      'No hacking on RCC surface.',
      'No chicken mesh at joints.',
      'Poor curing.',
      'Excess water in mortar.',
      'Uneven plaster thickness.',
    ],
    safety: [
      'Use safe scaffolding.',
      'Wear eye protection during hacking.',
      'Avoid working below unsafe plaster platform.',
    ],
  },
  {
    slug: 'waterproofing',
    title: 'Waterproofing Checklist',
    level: 'Intermediate',
    shortDesc:
      'Surface preparation, slope, corner treatment, coating, membrane, ponding test and leakage checklist.',
    tags: ['Waterproofing', 'Slope', 'Ponding', 'Leakage'],
    purpose:
      'Waterproofing checklist helps prevent leakage in terrace, bathroom, basement, balcony and water retaining structures.',
    beforeWork: [
      'Clean surface properly.',
      'Repair cracks and honeycombing.',
      'Check slope towards drain.',
      'Treat corners and pipe penetrations.',
      'Apply primer if required by system.',
    ],
    duringWork: [
      'Apply waterproofing material as per specification.',
      'Maintain required coating thickness.',
      'Treat joints and corners carefully.',
      'Protect membrane from damage.',
      'Avoid application on dusty or wet surface unless specified.',
    ],
    afterWork: [
      'Allow curing/drying as per product requirement.',
      'Conduct ponding test.',
      'Check leakage from bottom surface.',
      'Protect waterproofing layer before finishing work.',
    ],
    qualityChecks: [
      'Surface cleaning check',
      'Slope check',
      'Corner treatment check',
      'Coating thickness check',
      'Ponding test check',
    ],
    commonMistakes: [
      'Skipping surface preparation.',
      'No slope towards drain.',
      'Ignoring pipe joints.',
      'No ponding test.',
      'Damaging waterproofing during tile work.',
    ],
    safety: [
      'Use gloves while handling chemicals.',
      'Ensure ventilation in closed areas.',
      'Follow manufacturer safety instructions.',
    ],
  },
  {
    slug: 'painting',
    title: 'Painting Checklist',
    level: 'Basic',
    shortDesc:
      'Surface preparation, putty, primer, paint coats, shade approval and finishing checklist.',
    tags: ['Paint', 'Primer', 'Putty', 'Finish'],
    purpose:
      'Painting checklist ensures smooth surface, correct primer, approved shade and proper final finish.',
    beforeWork: [
      'Check plaster surface is dry.',
      'Remove dust, oil and loose particles.',
      'Repair cracks and undulations.',
      'Apply putty where required.',
      'Approve paint shade sample.',
    ],
    duringWork: [
      'Apply primer uniformly.',
      'Allow proper drying time between coats.',
      'Apply paint coats as specified.',
      'Check roller/brush marks.',
      'Protect floor and fixtures from stains.',
    ],
    afterWork: [
      'Check final shade and finish.',
      'Check patch marks.',
      'Clean paint stains.',
      'Do final touch-up before handover.',
    ],
    qualityChecks: [
      'Surface dryness check',
      'Primer check',
      'Shade approval check',
      'Coat thickness/coverage check',
      'Final finish check',
    ],
    commonMistakes: [
      'Painting on damp surface.',
      'No primer.',
      'Poor surface preparation.',
      'Uneven shade.',
      'Insufficient drying time.',
    ],
    safety: [
      'Ensure ventilation.',
      'Use mask where required.',
      'Keep paint away from fire source.',
    ],
  },
  {
    slug: 'finishing',
    title: 'Finishing Checklist',
    level: 'Basic to Intermediate',
    shortDesc:
      'Final finishing checklist for flooring, doors, windows, plumbing, electrical, cleaning and handover.',
    tags: ['Finishing', 'Handover', 'Snag', 'Quality'],
    purpose:
      'Finishing checklist helps verify final quality before client handover and reduces post-handover complaints.',
    beforeWork: [
      'Prepare finishing work schedule.',
      'Check material approvals.',
      'Ensure previous civil work is completed.',
      'Coordinate electrical, plumbing and carpentry teams.',
    ],
    duringWork: [
      'Check flooring level and joints.',
      'Check door and window alignment.',
      'Verify plumbing fixtures.',
      'Verify electrical switches and lights.',
      'Check wall finish and paint quality.',
    ],
    afterWork: [
      'Prepare snag list.',
      'Complete rectification work.',
      'Clean site properly.',
      'Check all rooms before handover.',
      'Take client approval/sign-off.',
    ],
    qualityChecks: [
      'Flooring finish check',
      'Door-window alignment check',
      'Electrical point check',
      'Plumbing fixture check',
      'Final cleaning check',
    ],
    commonMistakes: [
      'No snag list before handover.',
      'Ignoring minor cracks and stains.',
      'Poor coordination between trades.',
      'No final cleaning.',
      'Handover without testing fixtures.',
    ],
    safety: [
      'Keep floor clean to avoid slipping.',
      'Use proper ladder for finishing work.',
      'Check electrical safety before testing points.',
    ],
  },
]
