export const constructionStages = [
  {
    slug: 'land-purchase',
    title: 'Land Purchase',
    level: 'Planning',
    shortDesc: 'Land selection, document verification, soil condition and legal checking before construction.',
    tags: ['Land', 'Legal', 'Planning'],
    purpose:
      'Land purchase is the first stage where plot location, ownership documents, access road, soil condition and development potential are checked.',
    materials: [
      'Land documents',
      'Survey records',
      'Ownership papers',
      'Zoning information',
      'Soil investigation report if available',
    ],
    checklist: [
      'Check clear land title.',
      'Verify ownership and sale deed.',
      'Check access road availability.',
      'Check plot boundary and dimensions.',
      'Confirm land use/zoning.',
      'Check electricity, water and drainage availability.',
    ],
    qualityChecks: [
      'Boundary verification',
      'Document verification',
      'Site access check',
      'Flood/waterlogging risk check',
      'Soil condition observation',
    ],
    commonMistakes: [
      'Buying land without title verification.',
      'Ignoring access road width.',
      'Not checking zoning rules.',
      'Ignoring soil and waterlogging issues.',
    ],
  },
  {
    slug: 'planning',
    title: 'Planning & Design',
    level: 'Planning',
    shortDesc: 'Architectural planning, structural design, estimation and construction schedule preparation.',
    tags: ['Plan', 'Design', 'Estimate'],
    purpose:
      'Planning stage converts project requirement into architectural drawings, structural drawings, cost estimate and construction schedule.',
    materials: [
      'Architectural drawings',
      'Structural drawings',
      'Soil report',
      'BOQ estimate',
      'Construction schedule',
    ],
    checklist: [
      'Prepare architectural layout.',
      'Finalize room sizes and circulation.',
      'Prepare structural design.',
      'Prepare BOQ and cost estimate.',
      'Check local building rules.',
      'Plan construction sequence.',
    ],
    qualityChecks: [
      'Drawing coordination check',
      'Column grid check',
      'Structural drawing check',
      'BOQ quantity check',
      'Budget check',
    ],
    commonMistakes: [
      'Starting work without final drawings.',
      'No structural design.',
      'Poor coordination between architectural and structural drawings.',
      'No proper cost estimate.',
    ],
  },
  {
    slug: 'approval',
    title: 'Building Approval',
    level: 'Legal',
    shortDesc: 'Building permission, local authority approval, NOC and required construction permissions.',
    tags: ['Approval', 'Rules', 'NOC'],
    purpose:
      'Approval stage ensures the building plan follows local authority rules before construction starts.',
    materials: [
      'Approved drawings',
      'Application forms',
      'Ownership documents',
      'NOC documents',
      'Fee receipts',
    ],
    checklist: [
      'Submit drawings to local authority.',
      'Check setback, height and FSI/FAR.',
      'Get required NOCs.',
      'Confirm approval conditions.',
      'Keep approved drawings on site.',
    ],
    qualityChecks: [
      'Approved plan check',
      'Setback rule check',
      'Height rule check',
      'Parking rule check',
      'Fire/safety rule check if applicable',
    ],
    commonMistakes: [
      'Starting construction without approval.',
      'Changing plan without revision approval.',
      'Ignoring setback rules.',
      'Not keeping approved plan on site.',
    ],
  },
  {
    slug: 'excavation',
    title: 'Excavation',
    level: 'Execution',
    shortDesc: 'Site marking, foundation excavation, depth checking, soil removal and safety barricading.',
    tags: ['Earthwork', 'Level', 'Foundation'],
    purpose:
      'Excavation creates the required foundation pit or trench as per structural drawing and foundation level.',
    materials: [
      'Line marking tools',
      'Excavator/manual tools',
      'Level instrument',
      'Barricading tape',
      'Dewatering pump if required',
    ],
    checklist: [
      'Mark foundation lines correctly.',
      'Check excavation depth.',
      'Maintain side slope or shoring if required.',
      'Remove loose soil from bottom.',
      'Keep excavated soil away from edge.',
      'Get approval before PCC.',
    ],
    qualityChecks: [
      'Length, width and depth check',
      'Bottom level check',
      'Soil condition check',
      'Dewatering check',
      'Safety barricading check',
    ],
    commonMistakes: [
      'Wrong marking.',
      'Over excavation.',
      'No barricading.',
      'PCC placed over loose soil.',
    ],
  },
  {
    slug: 'foundation',
    title: 'Foundation',
    level: 'Execution',
    shortDesc: 'PCC, footing reinforcement, shuttering, concrete pouring and curing of foundation.',
    tags: ['Footing', 'PCC', 'RCC'],
    purpose:
      'Foundation transfers building load safely to the soil. Correct reinforcement, cover and concrete quality are critical.',
    materials: [
      'Cement',
      'Sand',
      'Aggregate',
      'Steel reinforcement',
      'Cover blocks',
      'Shuttering material',
      'Concrete',
    ],
    checklist: [
      'Check PCC level and thickness.',
      'Verify footing size.',
      'Check reinforcement diameter and spacing.',
      'Provide cover blocks.',
      'Check column starter bars.',
      'Pour concrete with proper vibration.',
    ],
    qualityChecks: [
      'Rebar spacing check',
      'Cover check',
      'Column starter alignment',
      'Concrete grade check',
      'Curing check',
    ],
    commonMistakes: [
      'Wrong footing size.',
      'Insufficient cover.',
      'Starter bars not aligned.',
      'Poor vibration causing honeycombing.',
    ],
  },
  {
    slug: 'column-beam-slab',
    title: 'Column, Beam & Slab',
    level: 'Structural',
    shortDesc: 'RCC frame construction including column, beam, slab reinforcement, shuttering and concrete.',
    tags: ['RCC', 'Frame', 'Concrete'],
    purpose:
      'Columns, beams and slabs form the main structural frame of the building and carry gravity and lateral loads.',
    materials: [
      'Steel reinforcement',
      'Concrete',
      'Shuttering plywood',
      'Props and staging',
      'Binding wire',
      'Cover blocks',
    ],
    checklist: [
      'Check column alignment and verticality.',
      'Verify beam reinforcement.',
      'Check slab bar spacing.',
      'Check shuttering level and support.',
      'Check electrical conduits before slab casting.',
      'Ensure proper vibration and curing.',
    ],
    qualityChecks: [
      'Reinforcement check',
      'Stirrup spacing check',
      'Cover check',
      'Shuttering level check',
      'Concrete compaction check',
    ],
    commonMistakes: [
      'Wrong stirrup spacing.',
      'Missing top extra bars.',
      'Poor slab level.',
      'Early removal of props.',
      'Poor curing.',
    ],
  },
  {
    slug: 'brickwork',
    title: 'Brickwork / Blockwork',
    level: 'Masonry',
    shortDesc: 'Wall construction using bricks or blocks with mortar, line, level and curing checks.',
    tags: ['Wall', 'Masonry', 'Mortar'],
    purpose:
      'Brickwork or blockwork creates external and internal walls as per layout and architectural requirement.',
    materials: [
      'Bricks or blocks',
      'Cement',
      'Sand',
      'Water',
      'Line thread',
      'Masonry tools',
    ],
    checklist: [
      'Check wall layout.',
      'Soak bricks if required.',
      'Prepare correct mortar ratio.',
      'Maintain line and plumb.',
      'Keep uniform joint thickness.',
      'Cure masonry properly.',
    ],
    qualityChecks: [
      'Line and plumb check',
      'Mortar ratio check',
      'Joint thickness check',
      'Brick/block quality check',
      'Curing check',
    ],
    commonMistakes: [
      'Using dry bricks.',
      'Thick mortar joints.',
      'Wall not in plumb.',
      'No curing.',
    ],
  },
  {
    slug: 'plaster-flooring-painting',
    title: 'Plaster, Flooring & Painting',
    level: 'Finishing',
    shortDesc: 'Surface finishing stage including plaster, tiles/flooring, putty, primer and painting.',
    tags: ['Plaster', 'Flooring', 'Paint'],
    purpose:
      'Finishing stage improves surface quality, appearance and usability of the building.',
    materials: [
      'Cement mortar',
      'Chicken mesh',
      'Tiles/flooring material',
      'Tile adhesive',
      'Putty',
      'Primer',
      'Paint',
    ],
    checklist: [
      'Clean wall surface before plaster.',
      'Fix chicken mesh at RCC-masonry joints.',
      'Check plaster thickness.',
      'Check flooring level and slope.',
      'Apply primer before paint.',
      'Check final finish and shade.',
    ],
    qualityChecks: [
      'Plaster level check',
      'Hollowness check',
      'Tile lippage check',
      'Painting surface check',
      'Final finish check',
    ],
    commonMistakes: [
      'No chicken mesh at joints.',
      'Poor plaster curing.',
      'Uneven flooring.',
      'Painting on damp surface.',
    ],
  },
  {
    slug: 'electrical-plumbing',
    title: 'Electrical & Plumbing',
    level: 'MEP',
    shortDesc: 'Electrical conduits, wiring, plumbing lines, pressure testing and fixture installation.',
    tags: ['Electrical', 'Plumbing', 'MEP'],
    purpose:
      'MEP stage provides functional electrical, water supply, drainage and sanitary systems in the building.',
    materials: [
      'Electrical conduits',
      'Wires and cables',
      'Switch boxes',
      'Water supply pipes',
      'Drainage pipes',
      'Sanitary fixtures',
    ],
    checklist: [
      'Check electrical conduit route.',
      'Pressure test plumbing lines.',
      'Check drainage slope.',
      'Coordinate wall chasing before plaster.',
      'Test electrical points.',
      'Check fixture alignment.',
    ],
    qualityChecks: [
      'Conduit placement check',
      'Wire size check',
      'Pipe pressure test',
      'Drainage slope check',
      'Fixture leakage check',
    ],
    commonMistakes: [
      'No pressure testing.',
      'Wrong drainage slope.',
      'Poor coordination before plaster.',
      'Loose electrical connections.',
    ],
  },
  {
    slug: 'handover',
    title: 'Finishing & Handover',
    level: 'Final',
    shortDesc: 'Final cleaning, snag list, testing, rectification and client handover process.',
    tags: ['Snag', 'Final Check', 'Handover'],
    purpose:
      'Handover stage ensures the building is complete, tested, cleaned and ready for use.',
    materials: [
      'Snag list',
      'Cleaning tools',
      'Testing checklist',
      'Warranty documents',
      'Final drawings if required',
    ],
    checklist: [
      'Prepare final snag list.',
      'Check doors, windows and fixtures.',
      'Test electrical and plumbing points.',
      'Clean all rooms.',
      'Complete rectification work.',
      'Take client approval/sign-off.',
    ],
    qualityChecks: [
      'Final finish check',
      'Electrical testing',
      'Plumbing testing',
      'Door-window operation check',
      'Cleaning and handover check',
    ],
    commonMistakes: [
      'Handover without snag list.',
      'No final testing.',
      'Poor cleaning.',
      'Ignoring minor defects before handover.',
    ],
  },
]
