export const metadata = {
  title: 'Terms & Conditions',
  description:
    'Terms and Conditions for CivilCalc Pro - Rules, responsibilities, and usage guidelines for our engineering platform.',
}

export default function TermsAndConditionsPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-4">Terms & Conditions</h1>

        <p className="text-slate-400 mb-10">
          Last Updated: {new Date().toLocaleDateString('en-IN')}
        </p>

        <div className="space-y-8 text-slate-300 leading-7">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-3">
              Acceptance of Terms
            </h2>

            <p>
              By accessing and using CivilCalc Pro, you agree to comply with and
              be bound by these Terms & Conditions. If you do not agree with
              these terms, please do not use the platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-3">
              Use of CivilCalc Pro
            </h2>

            <p>
              CivilCalc Pro provides civil engineering calculators, structural
              design tools, estimation tools, and related engineering resources.
              The platform is intended for educational, estimation, and
              professional assistance purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-3">
              Engineering Disclaimer
            </h2>

            <p>
              All calculations, reports, recommendations, and results generated
              by CivilCalc Pro are provided for guidance and estimation
              purposes only.
            </p>

            <p className="mt-3">
              Users must independently verify all calculations, engineering
              designs, quantities, structural details, and project-related
              decisions in accordance with applicable codes, standards, and
              professional engineering practices.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-3">
              No Professional Engineering Advice
            </h2>

            <p>
              CivilCalc Pro does not replace the services of a licensed
              engineer, architect, consultant, contractor, or other qualified
              professional.
            </p>

            <p className="mt-3">
              Use of this platform does not create any professional-client
              relationship.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-3">
              User Responsibility
            </h2>

            <p>
              Users are solely responsible for interpreting and applying the
              results generated by CivilCalc Pro. Any decisions made using the
              platform are entirely the responsibility of the user.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-3">
              Intellectual Property
            </h2>

            <p>
              All website content, software, branding, calculators, designs,
              graphics, reports, logos, and intellectual property associated
              with CivilCalc Pro remain the property of CivilCalc Pro unless
              otherwise stated.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-3">
              Limitation of Liability
            </h2>

            <p>
              CivilCalc Pro shall not be liable for any direct, indirect,
              incidental, special, consequential, or project-related damages,
              including construction errors, cost overruns, delays, losses, or
              engineering decisions arising from the use of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-3">
              Platform Availability
            </h2>

            <p>
              We strive to maintain uninterrupted service; however, CivilCalc
              Pro does not guarantee continuous availability and may modify,
              suspend, or discontinue features without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-3">
              Updates to These Terms
            </h2>

            <p>
              We may revise these Terms & Conditions from time to time. Updated
              versions will be posted on this page and become effective
              immediately upon publication.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-3">
              Contact Information
            </h2>

            <div className="mt-4 p-4 rounded-xl bg-slate-900 border border-slate-800">
              <p>Email: civilcal592005@gmail.com.com</p>
              <p>Website: https://civilcalcpro.in</p>
            </div>
          </section>
        </div>
      </div>
    </main>
  )
}
