export const materials = [
  {
    slug: 'cement',
    title: 'Cement',
    shortDesc: 'Cement types, uses, storage, quality checks and common site mistakes.',
    intro:
      'Cement is a binding material used in concrete, mortar, plaster and many construction works. It reacts with water and binds fine and coarse aggregates together.',
    types: [
      'Ordinary Portland Cement',
      'Portland Pozzolana Cement',
      'Portland Slag Cement',
      'Rapid Hardening Cement',
      'Sulphate Resisting Cement',
      'White Cement',
    ],
    properties: [
      'Good binding property',
      'Fineness affects strength development',
      'Initial and final setting time are important',
      'Strength increases with proper curing',
      'Must be protected from moisture',
    ],
    uses: [
      'RCC work',
      'PCC work',
      'Brick masonry mortar',
      'Plastering work',
      'Flooring and repair work',
      'Precast concrete elements',
    ],
    advantages: [
      'Easily available',
      'High strength when used properly',
      'Suitable for almost all civil construction works',
      'Can be used with admixtures for better performance',
    ],
    disadvantages: [
      'Can lose strength if stored badly',
      'Requires proper water-cement ratio',
      'Needs curing for strength gain',
      'Can crack due to shrinkage if workmanship is poor',
    ],
    storage: [
      'Store cement bags in a dry place',
      'Keep bags above floor level on wooden pallets',
      'Maintain gap from walls',
      'Do not store directly on ground',
      'Use old stock first',
      'Avoid long storage duration',
    ],
    qualityChecks: [
      'Cement should feel smooth when rubbed between fingers',
      'No hard lumps should be present',
      'Bag should not be damaged or wet',
      'Manufacturing date should be checked',
      'Colour should be uniform',
    ],
    labTests: [
      'Fineness test',
      'Standard consistency test',
      'Initial and final setting time test',
      'Soundness test',
      'Compressive strength test',
    ],
    fieldTests: [
      'Lump check',
      'Float test',
      'Hand feel test',
      'Date and bag condition check',
      'Colour uniformity check',
    ],
    isCodes: [
      'IS 269 - Ordinary Portland Cement',
      'IS 1489 - Portland Pozzolana Cement',
      'IS 455 - Portland Slag Cement',
      'IS 4031 - Cement testing methods',
    ],
    commonMistakes: [
      'Using old or lumpy cement',
      'Storing cement near water or damp walls',
      'Adding extra water in concrete',
      'Not curing concrete properly',
      'Using cement without checking manufacturing date',
    ],
    faqs: [
      {
        q: 'Which cement is commonly used for residential construction?',
        a: 'OPC and PPC are commonly used. PPC is widely used for general residential construction due to better workability and durability.',
      },
      {
        q: 'Can old cement be used?',
        a: 'Old cement should be checked carefully. If it has lumps or poor strength, it should not be used for important RCC work.',
      },
    ],
    relatedTools: [
      {
        name: 'Concrete Calculator',
        href: '/dashboard/calculators/concrete-volume',
      },
      {
        name: 'BOQ Generator',
        href: '/dashboard/calculators/boq-generator',
      },
    ],
  },
  {
    slug: 'steel',
    title: 'Steel',
    shortDesc: 'Steel reinforcement guide for RCC, bar types, tests, storage and mistakes.',
    intro:
      'Steel reinforcement is used in RCC to resist tensile stresses. Concrete is strong in compression, while steel helps in tension and bending resistance.',
    types: [
      'Mild steel bars',
      'HYSD bars',
      'TMT bars',
      'Structural steel sections',
      'Prestressing steel',
    ],
    properties: [
      'High tensile strength',
      'Ductility',
      'Good bond with concrete',
      'Bendability',
      'Corrosion resistance depends on protection and cover',
    ],
    uses: [
      'RCC beams',
      'RCC columns',
      'Slabs',
      'Footings',
      'Staircases',
      'Retaining walls',
      'Structural steel work',
    ],
    advantages: [
      'High tensile strength',
      'Suitable for RCC design',
      'Available in different diameters',
      'Easy to bend and place on site',
    ],
    disadvantages: [
      'Can corrode if cover is insufficient',
      'Needs proper cutting, bending and placing',
      'Cost fluctuates',
      'Improper lap length can reduce structural safety',
    ],
    storage: [
      'Store steel above ground level',
      'Avoid direct contact with soil',
      'Keep bars sorted by diameter',
      'Avoid excessive rusting',
      'Cover steel during rain if possible',
    ],
    qualityChecks: [
      'Check diameter of bars',
      'Check brand and grade marking',
      'Check rust condition',
      'Check bendability',
      'Check weight per meter if required',
    ],
    labTests: [
      'Tensile strength test',
      'Bend test',
      'Rebend test',
      'Elongation test',
      'Chemical composition test',
    ],
    fieldTests: [
      'Diameter check',
      'Weight per meter check',
      'Rust inspection',
      'Bend check',
      'Visual check for cracks or damage',
    ],
    isCodes: [
      'IS 1786 - High strength deformed steel bars and wires for concrete reinforcement',
      'IS 800 - General construction in steel',
      'IS 432 - Mild steel and medium tensile steel bars',
    ],
    commonMistakes: [
      'Providing insufficient cover',
      'Wrong bar spacing',
      'Incorrect lap length',
      'Cutting bars without bar bending schedule',
      'Using heavily rusted reinforcement',
    ],
    faqs: [
      {
        q: 'Why is steel used in RCC?',
        a: 'Steel is used because concrete is weak in tension. Steel takes tensile stress and improves bending resistance.',
      },
      {
        q: 'Is rusted steel acceptable?',
        a: 'Light surface rust may be acceptable after cleaning, but heavy flaky rust should be avoided.',
      },
    ],
    relatedTools: [
      {
        name: 'Steel Weight Calculator',
        href: '/dashboard/calculators/steel-weight',
      },
      {
        name: 'BBS Generator',
        href: '/dashboard/calculators/bbs-generator',
      },
    ],
  },
  {
    slug: 'sand',
    title: 'Sand',
    shortDesc: 'Sand types, properties, silt check, uses, storage and quality control.',
    intro:
      'Sand is a fine aggregate used in concrete, mortar, plaster and flooring work. Its grading, cleanliness and silt content directly affect construction quality.',
    types: ['River sand', 'M-sand', 'Pit sand', 'Plaster sand'],
    properties: [
      'Clean and free from organic impurities',
      'Proper grading',
      'Low silt content',
      'Good particle shape',
      'Suitable fineness for intended work',
    ],
    uses: [
      'Concrete production',
      'Brickwork mortar',
      'Plastering',
      'Flooring bedding',
      'PCC and masonry work',
    ],
    advantages: [
      'Improves workability',
      'Fills voids in concrete and mortar',
      'Available in different grades',
      'M-sand can be a controlled alternative',
    ],
    disadvantages: [
      'High silt content reduces strength',
      'Poor grading increases cement demand',
      'Wet sand causes bulking issue',
      'Impurities can affect durability',
    ],
    storage: [
      'Store on clean hard surface',
      'Avoid mixing with soil',
      'Keep separate from aggregate',
      'Protect from contamination',
    ],
    qualityChecks: [
      'Check silt content',
      'Check organic impurities',
      'Check particle size',
      'Check clay lumps',
      'Check moisture condition',
    ],
    labTests: [
      'Sieve analysis',
      'Silt content test',
      'Specific gravity test',
      'Water absorption test',
      'Bulking of sand test',
    ],
    fieldTests: [
      'Bottle silt test',
      'Hand rubbing test',
      'Visual impurity check',
      'Moisture check',
    ],
    isCodes: ['IS 383 - Coarse and fine aggregate for concrete', 'IS 2386 - Aggregate testing methods'],
    commonMistakes: [
      'Using sand with high silt content',
      'Not adjusting for bulking',
      'Mixing sand with soil on site',
      'Using wrong sand for plaster',
    ],
    faqs: [
      {
        q: 'Why is silt harmful in sand?',
        a: 'Excess silt reduces bonding and strength of concrete or mortar.',
      },
    ],
    relatedTools: [
      {
        name: 'Plaster Calculator',
        href: '/dashboard/calculators/plaster',
      },
      {
        name: 'Brickwork Calculator',
        href: '/dashboard/calculators/brickwork',
      },
    ],
  },
  {
    slug: 'aggregate',
    title: 'Aggregate',
    shortDesc: 'Coarse aggregate guide, grading, size, quality checks and tests.',
    intro:
      'Aggregate is used as a major volume component in concrete. Proper aggregate size, shape and grading improve concrete strength, workability and durability.',
    types: ['10 mm aggregate', '20 mm aggregate', '40 mm aggregate', 'Crushed stone aggregate', 'Gravel aggregate'],
    properties: [
      'Good crushing strength',
      'Proper grading',
      'Angular or cubical shape preferred',
      'Clean surface',
      'Low water absorption',
    ],
    uses: ['RCC concrete', 'PCC work', 'Road construction', 'Drainage layer', 'Mass concrete'],
    advantages: [
      'Provides bulk to concrete',
      'Improves compressive strength',
      'Reduces cement paste requirement',
      'Economical material',
    ],
    disadvantages: [
      'Poor grading affects workability',
      'Flaky aggregate reduces strength',
      'Dirty aggregate weakens bond',
      'Oversized aggregate causes placement issues',
    ],
    storage: [
      'Store on hard clean surface',
      'Keep different sizes separate',
      'Avoid soil contamination',
      'Avoid mixing with sand',
    ],
    qualityChecks: [
      'Check size and grading',
      'Check dust and clay',
      'Check flaky particles',
      'Check moisture and cleanliness',
    ],
    labTests: [
      'Sieve analysis',
      'Aggregate crushing value test',
      'Impact value test',
      'Abrasion value test',
      'Specific gravity and water absorption test',
    ],
    fieldTests: [
      'Visual grading check',
      'Dust check',
      'Size check',
      'Cleanliness check',
    ],
    isCodes: ['IS 383 - Coarse and fine aggregate for concrete', 'IS 2386 - Aggregate testing methods'],
    commonMistakes: [
      'Using dirty aggregate',
      'Using wrong size aggregate',
      'Not controlling moisture',
      'Mixing different sizes randomly',
    ],
    faqs: [
      {
        q: 'Which aggregate size is common for RCC?',
        a: '20 mm nominal size aggregate is commonly used for RCC work, depending on member size and reinforcement spacing.',
      },
    ],
    relatedTools: [
      {
        name: 'Concrete Calculator',
        href: '/dashboard/calculators/concrete-volume',
      },
    ],
  },
  {
    slug: 'bricks',
    title: 'Bricks',
    shortDesc: 'Brick types, uses, field tests, storage and common masonry mistakes.',
    intro:
      'Bricks are masonry units used in walls, partitions and building construction. Good bricks should be uniform, hard, well burnt and free from cracks.',
    types: ['First class bricks', 'Second class bricks', 'Fly ash bricks', 'AAC blocks', 'Concrete blocks'],
    properties: [
      'Uniform shape and size',
      'Good compressive strength',
      'Low water absorption',
      'No cracks',
      'Proper burning',
    ],
    uses: ['Load bearing walls', 'Partition walls', 'Boundary walls', 'Masonry work', 'Architectural work'],
    advantages: [
      'Easy to handle',
      'Locally available',
      'Good fire resistance',
      'Suitable for masonry construction',
    ],
    disadvantages: [
      'Quality varies by manufacturer',
      'Water absorption can be high',
      'Needs skilled masonry work',
      'Poor bricks cause cracks and dampness',
    ],
    storage: [
      'Stack bricks on level ground',
      'Keep different types separate',
      'Avoid muddy storage area',
      'Sprinkle water before masonry if required',
    ],
    qualityChecks: [
      'Check size and shape',
      'Check cracks',
      'Check sound by striking two bricks',
      'Check water absorption',
      'Check efflorescence',
    ],
    labTests: [
      'Compressive strength test',
      'Water absorption test',
      'Efflorescence test',
      'Dimension tolerance test',
    ],
    fieldTests: [
      'Soundness test',
      'Drop test',
      'Visual crack check',
      'Hardness check',
      'Water absorption rough check',
    ],
    isCodes: [
      'IS 1077 - Common burnt clay building bricks',
      'IS 3495 - Tests for burnt clay building bricks',
      'IS 12894 - Fly ash lime bricks',
    ],
    commonMistakes: [
      'Using overburnt or underburnt bricks',
      'Not soaking bricks before masonry',
      'Poor mortar joint thickness',
      'No proper curing after brickwork',
    ],
    faqs: [
      {
        q: 'Why are bricks soaked before masonry?',
        a: 'Bricks are soaked so they do not absorb water from mortar quickly, which improves bonding.',
      },
    ],
    relatedTools: [
      {
        name: 'Brickwork Calculator',
        href: '/dashboard/calculators/brickwork',
      },
    ],
  },
  {
    slug: 'blocks',
    title: 'Blocks',
    shortDesc: 'AAC blocks, concrete blocks, uses, checks and construction mistakes.',
    intro:
      'Blocks are larger masonry units used for faster wall construction. AAC blocks and concrete blocks are common alternatives to traditional clay bricks.',
    types: ['AAC blocks', 'Solid concrete blocks', 'Hollow concrete blocks', 'Fly ash blocks'],
    properties: [
      'Larger size than bricks',
      'Faster construction',
      'Better dimensional accuracy',
      'Lightweight in case of AAC blocks',
      'Good thermal insulation for AAC',
    ],
    uses: ['Partition walls', 'External walls', 'Residential buildings', 'Commercial buildings', 'Boundary walls'],
    advantages: [
      'Fast wall construction',
      'Less mortar consumption',
      'Better finish',
      'AAC blocks reduce dead load',
    ],
    disadvantages: [
      'Needs proper adhesive or mortar',
      'May require special anchoring for fixtures',
      'Poor workmanship causes cracks',
      'Water absorption and handling damage should be checked',
    ],
    storage: [
      'Store on level surface',
      'Avoid edge damage',
      'Keep away from excessive waterlogging',
      'Stack properly to prevent breakage',
    ],
    qualityChecks: [
      'Check dimensions',
      'Check broken edges',
      'Check density',
      'Check surface cracks',
      'Check manufacturer quality',
    ],
    labTests: ['Compressive strength test', 'Water absorption test', 'Density test', 'Dimension test'],
    fieldTests: ['Visual crack check', 'Dimension check', 'Edge damage check'],
    isCodes: [
      'IS 2185 - Concrete masonry units',
      'IS 2185 Part 3 - Autoclaved cellular aerated concrete blocks',
    ],
    commonMistakes: [
      'Using damaged blocks',
      'Not following proper joint thickness',
      'No chicken mesh at junctions',
      'Improper curing or wetting as per material type',
    ],
    faqs: [
      {
        q: 'Are AAC blocks good for residential buildings?',
        a: 'Yes, AAC blocks are commonly used because they are lightweight and provide faster construction, but proper workmanship is important.',
      },
    ],
    relatedTools: [
      {
        name: 'Brickwork Calculator',
        href: '/dashboard/calculators/brickwork',
      },
    ],
  },
  {
    slug: 'concrete',
    title: 'Concrete',
    shortDesc: 'Concrete grades, properties, uses, tests, curing and common problems.',
    intro:
      'Concrete is a composite material made from cement, sand, aggregate and water. It is used in RCC, PCC and many structural and non-structural works.',
    types: ['PCC', 'RCC', 'Ready mix concrete', 'High strength concrete', 'Self compacting concrete'],
    properties: [
      'Compressive strength',
      'Workability',
      'Durability',
      'Density',
      'Water-cement ratio control',
      'Setting and hardening behavior',
    ],
    uses: ['Footings', 'Columns', 'Beams', 'Slabs', 'Pavements', 'Retaining walls', 'Precast elements'],
    advantages: [
      'High compressive strength',
      'Can be moulded into different shapes',
      'Durable when designed and cured properly',
      'Economical for many structural works',
    ],
    disadvantages: [
      'Weak in tension without reinforcement',
      'Needs proper curing',
      'Can crack due to shrinkage',
      'Poor mix design causes honeycombing and segregation',
    ],
    storage: [
      'Concrete should be placed soon after mixing',
      'Materials should be stored separately and cleanly',
      'Avoid contamination of aggregates',
      'Protect fresh concrete from direct sun and rain',
    ],
    qualityChecks: [
      'Check grade of concrete',
      'Check slump/workability',
      'Check water-cement ratio',
      'Check compaction',
      'Check curing arrangement',
    ],
    labTests: ['Cube compressive strength test', 'Split tensile test', 'Flexural strength test'],
    fieldTests: ['Slump test', 'Temperature check', 'Visual segregation check', 'Compaction check'],
    isCodes: [
      'IS 456 - Plain and reinforced concrete',
      'IS 10262 - Concrete mix proportioning',
      'IS 1199 - Fresh concrete tests',
      'IS 516 - Strength tests of concrete',
    ],
    commonMistakes: [
      'Adding excess water',
      'Poor vibration',
      'No proper curing',
      'Concrete pouring from excessive height',
      'Wrong mix proportion',
    ],
    faqs: [
      {
        q: 'Why is curing important?',
        a: 'Curing helps concrete gain strength and reduces shrinkage cracks by maintaining moisture.',
      },
    ],
    relatedTools: [
      {
        name: 'Concrete Calculator',
        href: '/dashboard/calculators/concrete-volume',
      },
      {
        name: 'RCC Beam Design',
        href: '/dashboard/calculators/beam',
      },
    ],
  },
  {
    slug: 'fly-ash',
    title: 'Fly Ash',
    shortDesc: 'Fly ash use in concrete, bricks, advantages, tests and precautions.',
    intro:
      'Fly ash is a pozzolanic material used in cement, concrete and fly ash bricks. It can improve workability and durability when used properly.',
    types: ['Class F fly ash', 'Class C fly ash'],
    properties: [
      'Pozzolanic behavior',
      'Fine particle size',
      'Improves workability',
      'Can reduce heat of hydration',
      'Improves long-term durability',
    ],
    uses: ['PPC cement', 'Concrete mineral admixture', 'Fly ash bricks', 'Road embankments', 'Soil stabilization'],
    advantages: [
      'Improves workability',
      'Can improve durability',
      'Utilizes industrial by-product',
      'Can reduce cement consumption',
    ],
    disadvantages: [
      'Quality variation possible',
      'Early strength may be lower',
      'Needs proper mix design',
      'Improper use affects performance',
    ],
    storage: [
      'Store in dry condition',
      'Avoid contamination',
      'Use proper silos or covered storage',
    ],
    qualityChecks: [
      'Check fineness',
      'Check source reliability',
      'Check colour and consistency',
      'Check moisture condition',
    ],
    labTests: ['Fineness test', 'Chemical composition test', 'Pozzolanic activity test'],
    fieldTests: ['Visual consistency check', 'Moisture check', 'Source certificate check'],
    isCodes: ['IS 3812 - Pulverized fuel ash specification'],
    commonMistakes: [
      'Using unknown quality fly ash',
      'Replacing cement without design control',
      'Poor curing',
      'Not checking source certificate',
    ],
    faqs: [
      {
        q: 'Why is fly ash used in concrete?',
        a: 'Fly ash is used to improve workability, durability and reduce heat of hydration in suitable mixes.',
      },
    ],
    relatedTools: [
      {
        name: 'Concrete Calculator',
        href: '/dashboard/calculators/concrete-volume',
      },
    ],
  },
  {
    slug: 'admixture',
    title: 'Admixture',
    shortDesc: 'Concrete admixtures, uses, advantages, precautions and quality checks.',
    intro:
      'Admixtures are materials added to concrete before or during mixing to modify properties like workability, setting time, strength and durability.',
    types: [
      'Plasticizer',
      'Superplasticizer',
      'Retarder',
      'Accelerator',
      'Air entraining admixture',
      'Waterproofing admixture',
    ],
    properties: [
      'Improves workability',
      'Can reduce water demand',
      'Controls setting time',
      'Improves pumpability',
      'May improve durability',
    ],
    uses: [
      'Ready mix concrete',
      'High strength concrete',
      'Hot weather concreting',
      'Mass concrete',
      'Waterproof concrete',
    ],
    advantages: [
      'Better workability',
      'Lower water-cement ratio',
      'Improved pumpability',
      'Can help control setting time',
    ],
    disadvantages: [
      'Wrong dosage can harm concrete',
      'Compatibility issue with cement possible',
      'Needs proper trial mix',
      'Site overdosage is risky',
    ],
    storage: [
      'Store as per manufacturer instruction',
      'Avoid direct sunlight if not recommended',
      'Keep container sealed',
      'Do not use expired product',
    ],
    qualityChecks: [
      'Check product type',
      'Check expiry date',
      'Check dosage recommendation',
      'Check compatibility with cement',
      'Check manufacturer certificate',
    ],
    labTests: ['Trial mix test', 'Slump retention test', 'Setting time check', 'Compressive strength comparison'],
    fieldTests: ['Slump check', 'Visual segregation check', 'Dosage measurement check'],
    isCodes: ['IS 9103 - Concrete admixtures'],
    commonMistakes: [
      'Adding admixture without dosage control',
      'Using expired admixture',
      'No trial mix',
      'Mixing different admixtures randomly',
    ],
    faqs: [
      {
        q: 'Can admixture replace curing?',
        a: 'No. Admixture can improve concrete performance, but curing is still required.',
      },
    ],
    relatedTools: [
      {
        name: 'Concrete Calculator',
        href: '/dashboard/calculators/concrete-volume',
      },
    ],
  },
  {
    slug: 'waterproofing',
    title: 'Waterproofing',
    shortDesc: 'Waterproofing materials, uses, checks, methods and common mistakes.',
    intro:
      'Waterproofing is used to prevent water leakage and dampness in basements, terraces, bathrooms, water tanks and other exposed areas.',
    types: [
      'Cementitious waterproofing',
      'Liquid membrane waterproofing',
      'Bituminous coating',
      'PU waterproofing',
      'Crystalline waterproofing',
      'APP membrane',
    ],
    properties: [
      'Water resistance',
      'Adhesion',
      'Flexibility',
      'Crack bridging ability',
      'Durability against weathering',
    ],
    uses: ['Terrace', 'Bathroom', 'Basement', 'Water tank', 'Retaining wall', 'Balcony'],
    advantages: [
      'Prevents leakage',
      'Protects structure from dampness',
      'Improves durability',
      'Reduces repair cost',
    ],
    disadvantages: [
      'Needs skilled application',
      'Surface preparation is critical',
      'Wrong product selection causes failure',
      'Poor curing or protection damages treatment',
    ],
    storage: [
      'Store chemicals in sealed containers',
      'Avoid direct sunlight if required',
      'Follow manufacturer instructions',
      'Keep membranes protected from damage',
    ],
    qualityChecks: [
      'Check surface cleaning',
      'Check cracks and joints',
      'Check primer application',
      'Check coating thickness',
      'Check ponding test after completion',
    ],
    labTests: ['Material certificate check', 'Elongation test', 'Adhesion test', 'Water permeability test'],
    fieldTests: ['Ponding test', 'Visual coating check', 'Joint treatment check', 'Surface preparation check'],
    isCodes: ['Use relevant product standard and manufacturer technical datasheet for project-specific waterproofing system'],
    commonMistakes: [
      'Applying on dusty surface',
      'Ignoring corners and joints',
      'No slope on terrace',
      'Skipping ponding test',
      'Damaging coating during next work',
    ],
    faqs: [
      {
        q: 'Why does terrace waterproofing fail?',
        a: 'Common reasons are poor surface preparation, no slope, cracks, improper joint treatment and damage after application.',
      },
    ],
    relatedTools: [
      {
        name: 'BOQ Generator',
        href: '/dashboard/calculators/boq-generator',
      },
    ],
  },
]
